namespace Foggy.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulateGameCategoriesAndCountries : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Afghanistan', 'AF', 'AFG', 004)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Albania', 'AL', 'ALB', 008)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Algeria', 'DZ', 'DZA', 012)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('American Samoa', 'AS', 'ASM', 016)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Andorra', 'AD', 'AND', 020)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Angola', 'AO', 'AGO', 024)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Anguilla', 'AI', 'AIA', 660)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Antarctica', 'AQ', 'ATA', 010)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Antigua and Barbuda', 'AG', 'ATG', 028)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Argentina', 'AR', 'ARG', 032)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Armenia', 'AM', 'ARM', 051)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Aruba', 'AW', 'ABW', 533)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Australia', 'AU', 'AUS', 036)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Austria', 'AT', 'AUT', 040)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Azerbaijan', 'AZ', 'AZE', 031)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Bahamas (the)', 'BS', 'BHS', 044)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Bahrain', 'BH', 'BHR', 048)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Bangladesh', 'BD', 'BGD', 050)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Barbados', 'BB', 'BRB', 052)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Belarus', 'BY', 'BLR', 112)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Belgium', 'BE', 'BEL', 056)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Belize', 'BZ', 'BLZ', 084)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Benin', 'BJ', 'BEN', 204)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Bermuda', 'BM', 'BMU', 060)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Bhutan', 'BT', 'BTN', 064)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Bolivia (Plurinational State of)', 'BO', 'BOL', 068)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', 535)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Bosnia and Herzegovina', 'BA', 'BIH', 070)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Botswana', 'BW', 'BWA', 072)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Bouvet Island', 'BV', 'BVT', 074)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Brazil', 'BR', 'BRA', 076)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('British Indian Ocean Territory (the)', 'IO', 'IOT', 086)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Brunei Darussalam', 'BN', 'BRN', 096)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Bulgaria', 'BG', 'BGR', 100)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Burkina Faso', 'BF', 'BFA', 854)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Burundi', 'BI', 'BDI', 108)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Cabo Verde', 'CV', 'CPV', 132)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Cambodia', 'KH', 'KHM', 116)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Cameroon', 'CM', 'CMR', 120)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Canada', 'CA', 'CAN', 124)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Cayman Islands (the)', 'KY', 'CYM', 136)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Central African Republic (the)', 'CF', 'CAF', 140)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Chad', 'TD', 'TCD', 148)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Chile', 'CL', 'CHL', 152)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('China', 'CN', 'CHN', 156)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Christmas Island', 'CX', 'CXR', 162)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Cocos (Keeling) Islands (the)', 'CC', 'CCK', 166)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Colombia', 'CO', 'COL', 170)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Comoros (the)', 'KM', 'COM', 174)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Congo (the Democratic Republic of the)', 'CD', 'COD', 180)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Congo (the)', 'CG', 'COG', 178)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Cook Islands (the)', 'CK', 'COK', 184)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Costa Rica', 'CR', 'CRI', 188)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Croatia', 'HR', 'HRV', 191)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Cuba', 'CU', 'CUB', 192)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Curaçao', 'CW', 'CUW', 531)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Cyprus', 'CY', 'CYP', 196)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Czechia', 'CZ', 'CZE', 203)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Côte d\'\'Ivoire', 'CI', 'CIV', 384)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Denmark', 'DK', 'DNK', 208)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Djibouti', 'DJ', 'DJI', 262)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Dominica', 'DM', 'DMA', 212)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Dominican Republic (the)', 'DO', 'DOM', 214)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Ecuador', 'EC', 'ECU', 218)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Egypt', 'EG', 'EGY', 818)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('El Salvador', 'SV', 'SLV', 222)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Equatorial Guinea', 'GQ', 'GNQ', 226)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Eritrea', 'ER', 'ERI', 232)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Estonia', 'EE', 'EST', 233)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Eswatini', 'SZ', 'SWZ', 748)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Ethiopia', 'ET', 'ETH', 231)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Falkland Islands (the) [Malvinas]', 'FK', 'FLK', 238)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Faroe Islands (the)', 'FO', 'FRO', 234)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Fiji', 'FJ', 'FJI', 242)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Finland', 'FI', 'FIN', 246)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('France', 'FR', 'FRA', 250)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('French Guiana', 'GF', 'GUF', 254)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('French Polynesia', 'PF', 'PYF', 258)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('French Southern Territories (the)', 'TF', 'ATF', 260)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Gabon', 'GA', 'GAB', 266)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Gambia (the)', 'GM', 'GMB', 270)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Georgia', 'GE', 'GEO', 268)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Germany', 'DE', 'DEU', 276)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Ghana', 'GH', 'GHA', 288)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Gibraltar', 'GI', 'GIB', 292)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Greece', 'GR', 'GRC', 300)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Greenland', 'GL', 'GRL', 304)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Grenada', 'GD', 'GRD', 308)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Guadeloupe', 'GP', 'GLP', 312)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Guam', 'GU', 'GUM', 316)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Guatemala', 'GT', 'GTM', 320)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Guernsey', 'GG', 'GGY', 831)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Guinea', 'GN', 'GIN', 324)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Guinea-Bissau', 'GW', 'GNB', 624)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Guyana', 'GY', 'GUY', 328)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Haiti', 'HT', 'HTI', 332)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Heard Island and McDonald Islands', 'HM', 'HMD', 334)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Holy See (the)', 'VA', 'VAT', 336)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Honduras', 'HN', 'HND', 340)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Hong Kong', 'HK', 'HKG', 344)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Hungary', 'HU', 'HUN', 348)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Iceland', 'IS', 'ISL', 352)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('India', 'IN', 'IND', 356)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Indonesia', 'ID', 'IDN', 360)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Iran (Islamic Republic of)', 'IR', 'IRN', 364)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Iraq', 'IQ', 'IRQ', 368)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Ireland', 'IE', 'IRL', 372)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Isle of Man', 'IM', 'IMN', 833)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Israel', 'IL', 'ISR', 376)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Italy', 'IT', 'ITA', 380)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Jamaica', 'JM', 'JAM', 388)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Japan', 'JP', 'JPN', 392)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Jersey', 'JE', 'JEY', 832)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Jordan', 'JO', 'JOR', 400)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Kazakhstan', 'KZ', 'KAZ', 398)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Kenya', 'KE', 'KEN', 404)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Kiribati', 'KI', 'KIR', 296)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Korea (the Democratic People\'\'s Republic of)', 'KP', 'PRK', 408)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Korea (the Republic of)', 'KR', 'KOR', 410)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Kuwait', 'KW', 'KWT', 414)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Kyrgyzstan', 'KG', 'KGZ', 417)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Lao People\'\'s Democratic Republic (the)', 'LA', 'LAO', 418)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Latvia', 'LV', 'LVA', 428)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Lebanon', 'LB', 'LBN', 422)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Lesotho', 'LS', 'LSO', 426)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Liberia', 'LR', 'LBR', 430)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Libya', 'LY', 'LBY', 434)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Liechtenstein', 'LI', 'LIE', 438)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Lithuania', 'LT', 'LTU', 440)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Luxembourg', 'LU', 'LUX', 442)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Macao', 'MO', 'MAC', 446)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Madagascar', 'MG', 'MDG', 450)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Malawi', 'MW', 'MWI', 454)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Malaysia', 'MY', 'MYS', 458)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Maldives', 'MV', 'MDV', 462)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Mali', 'ML', 'MLI', 466)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Malta', 'MT', 'MLT', 470)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Marshall Islands (the)', 'MH', 'MHL', 584)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Martinique', 'MQ', 'MTQ', 474)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Mauritania', 'MR', 'MRT', 478)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Mauritius', 'MU', 'MUS', 480)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Mayotte', 'YT', 'MYT', 175)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Mexico', 'MX', 'MEX', 484)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Micronesia (Federated States of)', 'FM', 'FSM', 583)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Moldova (the Republic of)', 'MD', 'MDA', 498)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Monaco', 'MC', 'MCO', 492)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Mongolia', 'MN', 'MNG', 496)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Montenegro', 'ME', 'MNE', 499)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Montserrat', 'MS', 'MSR', 500)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Morocco', 'MA', 'MAR', 504)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Mozambique', 'MZ', 'MOZ', 508)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Myanmar', 'MM', 'MMR', 104)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Namibia', 'NA', 'NAM', 516)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Nauru', 'NR', 'NRU', 520)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Nepal', 'NP', 'NPL', 524)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Netherlands (the)', 'NL', 'NLD', 528)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('New Caledonia', 'NC', 'NCL', 540)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('New Zealand', 'NZ', 'NZL', 554)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Nicaragua', 'NI', 'NIC', 558)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Niger (the)', 'NE', 'NER', 562)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Nigeria', 'NG', 'NGA', 566)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Niue', 'NU', 'NIU', 570)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Norfolk Island', 'NF', 'NFK', 574)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Northern Mariana Islands (the)', 'MP', 'MNP', 580)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Norway', 'NO', 'NOR', 578)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Oman', 'OM', 'OMN', 512)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Pakistan', 'PK', 'PAK', 586)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Palau', 'PW', 'PLW', 585)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Palestine, State of', 'PS', 'PSE', 275)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Panama', 'PA', 'PAN', 591)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Papua New Guinea', 'PG', 'PNG', 598)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Paraguay', 'PY', 'PRY', 600)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Peru', 'PE', 'PER', 604)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Philippines (the)', 'PH', 'PHL', 608)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Pitcairn', 'PN', 'PCN', 612)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Poland', 'PL', 'POL', 616)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Portugal', 'PT', 'PRT', 620)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Puerto Rico', 'PR', 'PRI', 630)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Qatar', 'QA', 'QAT', 634)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Republic of North Macedonia', 'MK', 'MKD', 807)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Romania', 'RO', 'ROU', 642)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Russian Federation (the)', 'RU', 'RUS', 643)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Rwanda', 'RW', 'RWA', 646)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Réunion', 'RE', 'REU', 638)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Saint Barthélemy', 'BL', 'BLM', 652)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', 654)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Saint Kitts and Nevis', 'KN', 'KNA', 659)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Saint Lucia', 'LC', 'LCA', 662)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Saint Martin (French part)', 'MF', 'MAF', 663)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Saint Pierre and Miquelon', 'PM', 'SPM', 666)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Saint Vincent and the Grenadines', 'VC', 'VCT', 670)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Samoa', 'WS', 'WSM', 882)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('San Marino', 'SM', 'SMR', 674)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Sao Tome and Principe', 'ST', 'STP', 678)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Saudi Arabia', 'SA', 'SAU', 682)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Senegal', 'SN', 'SEN', 686)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Serbia', 'RS', 'SRB', 688)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Seychelles', 'SC', 'SYC', 690)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Sierra Leone', 'SL', 'SLE', 694)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Singapore', 'SG', 'SGP', 702)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Sint Maarten (Dutch part)', 'SX', 'SXM', 534)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Slovakia', 'SK', 'SVK', 703)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Slovenia', 'SI', 'SVN', 705)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Solomon Islands', 'SB', 'SLB', 090)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Somalia', 'SO', 'SOM', 706)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('South Africa', 'ZA', 'ZAF', 710)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('South Georgia and the South Sandwich Islands', 'GS', 'SGS', 239)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('South Sudan', 'SS', 'SSD', 728)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Spain', 'ES', 'ESP', 724)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Sri Lanka', 'LK', 'LKA', 144)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Sudan (the)', 'SD', 'SDN', 729)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Suriname', 'SR', 'SUR', 740)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Svalbard and Jan Mayen', 'SJ', 'SJM', 744)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Sweden', 'SE', 'SWE', 752)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Switzerland', 'CH', 'CHE', 756)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Syrian Arab Republic', 'SY', 'SYR', 760)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Taiwan (Province of China)', 'TW', 'TWN', 158)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Tajikistan', 'TJ', 'TJK', 762)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Tanzania, United Republic of', 'TZ', 'TZA', 834)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Thailand', 'TH', 'THA', 764)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Timor-Leste', 'TL', 'TLS', 626)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Togo', 'TG', 'TGO', 768)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Tokelau', 'TK', 'TKL', 772)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Tonga', 'TO', 'TON', 776)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Trinidad and Tobago', 'TT', 'TTO', 780)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Tunisia', 'TN', 'TUN', 788)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Turkey', 'TR', 'TUR', 792)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Turkmenistan', 'TM', 'TKM', 795)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Turks and Caicos Islands (the)', 'TC', 'TCA', 796)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Tuvalu', 'TV', 'TUV', 798)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Uganda', 'UG', 'UGA', 800)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Ukraine', 'UA', 'UKR', 804)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('United Arab Emirates (the)', 'AE', 'ARE', 784)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('United Kingdom of Great Britain', 'GB', 'GBR', 826)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('United States Minor Outlying Islands (the)', 'UM', 'UMI', 581)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('United States of America (the)', 'US', 'USA', 840)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Uruguay', 'UY', 'URY', 858)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Uzbekistan', 'UZ', 'UZB', 860)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Vanuatu', 'VU', 'VUT', 548)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Venezuela (Bolivarian Republic of)', 'VE', 'VEN', 862)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Viet Nam', 'VN', 'VNM', 704)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Virgin Islands (British)', 'VG', 'VGB', 092)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Virgin Islands (U.S.)', 'VI', 'VIR', 850)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Wallis and Futuna', 'WF', 'WLF', 876)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Western Sahara', 'EH', 'ESH', 732)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Yemen', 'YE', 'YEM', 887)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Zambia', 'ZM', 'ZMB', 894)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Zimbabwe', 'ZW', 'ZWE', 716)");
            Sql("INSERT INTO Countries (Name, Alpha2, Alpha3, UnCode) VALUES ('Åland Islands', 'AX', 'ALA', 248)");

            Sql("INSERT INTO GameCategories (Name) VALUES ('Indie')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Action')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Adventure')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Casual')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Simulation')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Strategy')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('RPG')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Early Access')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Singleplayer')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Free to Play')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('2D')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Violent')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Sports')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Massively Multiplayer')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Atmospheric')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Multiplayer')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Puzzle')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Racing')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Gore')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Story Rich')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Nudity')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Fantasy')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Sexual Content')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Great Soundtrack')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Anime')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Pixel Graphics')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Funny')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('First-Person')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Colorful')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Sci-fi')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('3D')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Horror')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Cute')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Shooter')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Arcade')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('VR')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Difficult')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Retro')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Exploration')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Family Friendly')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Co-op')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Survival')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Platformer')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Open World')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Relaxing')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Comedy')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('FPS')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Female Protagonist')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Online Co-Op')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Visual Novel')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Third Person')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Action-Adventure')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Design & Illustration')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Utilities')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Sandbox')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Realistic')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Physics')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('PvP')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Turn-Based')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Choices Matter')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Stylized')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Psychological Horror')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Top-Down')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Dark')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Mystery')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Space')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Replay Value')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Tactical')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Local Multiplayer')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Combat')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Point & Click')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Building')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Character Customization')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Cartoony')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Management')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Education')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Multiple Endings')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Minimalist')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Old School')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Controller')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Action RPG')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Mature')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Classic')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Survival Horror')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Zombies')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Crafting')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Side Scroller')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Futuristic')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('2D Platformer')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('PvE')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Puzzle Platformer')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Local Co-Op')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Movie')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Memes')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Shoot \'\'Em Up')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Procedural Generation')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Magic')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Roguelike')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Fast-Paced')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('War')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Resource Management')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Turn-Based Strategy')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Hand-drawn')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Web Publishing')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Cartoon')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Short')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Medieval')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Beautiful')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Party-Based RPG')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Hack and Slash')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Animation & Modeling')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Roguelite')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Historical')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Turn-Based Combat')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Software')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('JRPG')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Experimental')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Dark Fantasy')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Linear')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Dating Sim')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Walking Simulator')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Post-apocalyptic')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Romance')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Stealth')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Fighting')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Base Building')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Bullet Hell')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Drama')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Surreal')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('RTS')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Logic')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Choose Your Own Adventure')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('3D Platformer')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Dungeon Crawler')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Turn-Based Tactics')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Hidden Object')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Interactive Fiction')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Audio Production')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('RPGMaker')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Music')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Narration')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Military')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Third-Person Shooter')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Isometric')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Team-Based')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Top-Down Shooter')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Score Attack')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Cyberpunk')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Competitive')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Dark Humor')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Driving')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Robots')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Video Production')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('4 Player Local')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Text-Based')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Economy')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Aliens')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Moddable')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('1990s')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Card Game')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('2.5D')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Flight')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Hentai')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Tower Defense')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Abstract')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Character Action Game')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('1980s')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Perma Death')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('LGBTQ+')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Soundtrack')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Emotional')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('City Builder')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Cinematic')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Board Game')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Action Roguelike')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Beat \'\'em up')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Investigation')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Thriller')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Addictive')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Tutorial')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Detective')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Psychological')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Arena Shooter')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Destruction')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Nature')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Conversation')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Inventory Management')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Metroidvania')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Immersive Sim')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Game Development')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Real Time Tactics')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('World War II')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Level Editor')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Strategy RPG')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Nonlinear')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Loot')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Software Training')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('NSFW')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Demons')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('MMORPG')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Tabletop')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Psychedelic')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Modern')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Dystopian')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Time Management')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Alternate History')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Crime')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Wargame')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Tactical RPG')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Dark Comedy')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Blood')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Twin Stick Shooter')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Parkour')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Clicker')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Supernatural')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Life Sim')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Grand Strategy')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Artificial Intelligence')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Comic Book')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Lore-Rich')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Precision Platformer')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Illuminati')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Automobile Sim')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Open World Survival Craft')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('2D Fighter')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Science')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Episodic')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Epic')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Co-op Campaign')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Souls-like')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Real-Time')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Lovecraftian')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('CRPG')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Split Screen')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Runner')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Space Sim')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Cult Classic')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Philosophical')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Rhythm')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Mythology')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Mouse only')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Grid-Based Movement')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Photo Editing')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Swordplay')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Class-Based')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Battle Royale')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Match 3')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('3D Vision')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Gun Customization')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Dragons')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('eSports')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Parody')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Steampunk')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Political')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Satire')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Voxel')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Noir')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Bullet Time')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('6DOF')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('America')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Mechs')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('MOBA')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Deckbuilding')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Remake')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Cats')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Tanks')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Mining')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Trading')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Hunting')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Real-Time with Pause')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('4X')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Vehicular Combat')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Hacking')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Conspiracy')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Politics')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Pirates')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Card Battler')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Gothic')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Kickstarter')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Ninja')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Time Manipulation')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Otome')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Capitalism')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Cold War')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Colony Sim')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Time Travel')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Hex Grid')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('God Game')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Collectathon')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Trains')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Agriculture')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Superhero')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('GameMaker')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('3D Fighter')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Quick-Time Events')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Dinosaurs')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Word Game')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Experience')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Underground')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Martial Arts')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Mystery Dungeon')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Touch-Friendly')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('FMV')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Naval')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Dog')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Fishing')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Trading Card Game')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Western')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Mod')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Assassin')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Farming Sim')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Dynamic Narration')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Programming')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Documentary')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Minigames')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Heist')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Spectacle fighter')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Underwater')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Idler')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Automation')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Hero Shooter')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Asynchronous Multiplayer')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Combat Racing')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Immersive')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Dungeons & Dragons')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Diplomacy')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Sequel')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Vampire')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Archery')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Political Sim')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Games Workshop')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Faith')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Looter Shooter')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Naval Combat')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Gaming')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Sokoban')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Crowdfunded')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Party')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Narrative')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Solitaire')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Time Attack')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Silent Protagonist')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Sailing')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Soccer')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Party Game')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Villain Protagonist')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Sniper')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Football')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('World War I')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Snow')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Transportation')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Foreign')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('TrackIR')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Offroad')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('360 Video')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('On-Rails Shooter')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Typing')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Horses')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Gambling')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Mars')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Chess')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Pinball')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Transhumanism')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Creature Collector')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Boxing')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Trivia')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Werewolves')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('LEGO')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Unforgiving')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Farming')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Auto Battler')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Based On A Novel')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Traditional Roguelike')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Nostalgia')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Warhammer 40K')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Rome')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Motorbike')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Roguelike Deckbuilder')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Medical Sim')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Golf')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Electronic Music')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Ambient')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Jet')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Bikes')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Asymmetric VR')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Intentionally Awkward Controls')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Spaceships')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Basketball')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Outbreak Sim')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Spelling')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Submarine')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Steam Machine')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Cooking')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Roguevania')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Benchmark')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Mini Golf')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Social Deduction')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Pool')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Hardware')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Wrestling')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Instrumental Music')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Feature Film')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Baseball')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Tennis')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Lemmings')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Voice Control')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Skateboarding')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Electronic')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Hockey')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Cycling')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Bowling')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Rock Music')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Motocross')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Well-Written')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Skating')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('ATV')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('8-bit Music')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Skiing')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Reboot')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('BMX')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Snowboarding')");
            Sql("INSERT INTO GameCategories (Name) VALUES ('Action RTS')");
        }

        public override void Down()
        {
        }
    }
}
